CREATE TABLE PLACE(
    DRIVEID INT PRIMARY KEY,
    COMPNAME VARCHAR(255),
    PACKAGE INT,
    LOCATION VARCHAR(255)
);

CREATE TABLE STUDENT(
    SID INT PRIMARY KEY,
    SNAME VARCHAR(255),
    CGPA INT,
    SBRANCH VARCHAR(255),
    DRIVEID INT,
    FOREIGN KEY (DRIVEID) REFERENCES PLACE(DRIVEID)
);


-- ON DELETE CASCADE IMPORTANT
-- CREATE TABLE STUDENT1(
--     SID INT PRIMARY KEY,
--     SNAME VARCHAR(255),
--     CGPA INT,
--     SBRANCH VARCHAR(255),
--     DRIVEID INT,
--     FOREIGN KEY (DRIVEID) REFERENCES PLACE(DRIVEID) ON DELETE CASCADE
-- );

CREATE TABLE TRAINING(
    TID INT PRIMARY KEY,
    TCOMPNAME VARCHAR(255),
    TFEE INT,
    TYEAR DATE
);

-- CREATE TABLE TRAINING1(
--     TID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
--     TCOMPNAME VARCHAR(255),
--     TFEE INT,
--     TYEAR DATE
-- );
-- INSERT INTO TRAINING1 (TCOMPNAME,TFEE,TYEAR) VALUES("AMAZON",70000,"2019-10-10");
INSERT INTO PLACE VALUES(1,"BMC",15,"PUNE"),(2,"BNY",20,"PUNE"),(3,"MASTERCARD",25,"MUMBAI"),(4,"DB",19,"MUMBAI"),(5,"BMC",14,"PUNE");
INSERT INTO STUDENT VALUES(1,"ARYAN",9,"CE",1),(2,"ROHIT",9,"CE",1),(3,"SHARVI",10,"CE",2),(4,"NEHIL",8,"IT",1),(5,"ARUNIMA",9,"IT",2),(6,"MANSI",8,"CE",3),(7,"CHINMAY",7,"ENTC",4);
INSERT INTO TRAINING VALUES(1,"AMAZON",70000,"2019-10-10"),(2,"BNY",50000,"2020-8-10"),(3,"DB",75000,"2022-8-8"),(4,"BMC",90000,"2021-10-11"),(5,"MASTERCARD",40000,"2021-5-7");

INSERT INTO TRAINING1 (TCOMPNAME,TFEE,TYEAR) VALUES("AMAZON",70000,"2019-10-10");

SELECT * FROM PLACE;
SELECT * FROM STUDENT;
SELECT * FROM TRAINING;

SELECT * FROM STUDENT WHERE (SBRANCH='CE' OR SBRANCH='IT');
SELECT * FROM STUDENT WHERE (SBRANCH='CE' OR SBRANCH='IT') AND (SNAME LIKE 'A%' OR SNAME LIKE 'D%');
SELECT COUNT(DISTINCT TCOMPNAME) AS NUMBEROFCOMP FROM TRAINING;
SELECT DISTINCT TCOMPNAME FROM TRAINING;
UPDATE TRAINING SET TFEE=TFEE+0.15*TFEE WHERE TYEAR<"2020-10-10";
SELECT COMPNAME FROM PLACE WHERE LOCATION ='PUNE' OR LOCATION ='MUMBAI';
SELECT AVG(PACKAGE) AS AVERAGEPACKAGE FROM PLACE;
SELECT SNAME,CGPA FROM STUDENT WHERE CGPA = (SELECT MAX(CGPA) FROM STUDENT);
SELECT SNAME,CGPA FROM STUDENT WHERE CGPA BETWEEN 7 AND 9;
SELECT * FROM TRAINING ORDER BY TFEE DESC;
SELECT SNAME, COMPNAME, LOCATION, PACKAGE FROM STUDENT S, PLACE P WHERE (PACKAGE=15 OR PACKAGE=20) AND S.DRIVEID=P.DRIVEID;

CREATE VIEW NEW_VIEW AS SELECT SNAME,COMPNAME, LOCATION, PACKAGE FROM STUDENT S, PLACE P WHERE S.DRIVEID=P.DRIVEID;

-- UPDATE NEW_VIEW SET PACKAGE=55 WHERE SNAME='ARYAN';SOMETHING WRONG
INSERT INTO NEW_VIEW(SNAME,COMPNAME,LOCATION,PACKAGE) VALUES('AJ','BJ','CJ',77);
SELECT * FROM NEW_VIEW;

CREATE INDEX STUDENT_INDEX ON STUDENT(SID,SNAME);
