CREATE TABLE PLACE(
    DRIVEID INT PRIMARY KEY,
    COMPNAME VARCHAR(255),
    PACKAGE INT,
    LOCATION VARCHAR(255)
);

CREATE TABLE STUDENT(
    SID INT PRIMARY KEY,
    SNAME VARCHAR(255),
    CGPA INT,
    SBRANCH VARCHAR(255),
    DRIVEID INT,
    FOREIGN KEY (DRIVEID) REFERENCES PLACE(DRIVEID)
);
CREATE TABLE TRAINING2(
    TID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SID INT,
    TCOMPNAME VARCHAR(255),
    TFEE INT,
    TYEAR DATE,
    FOREIGN KEY (SID) REFERENCES STUDENT(SID) 
);

INSERT INTO TRAINING2 VALUES(1,1,"AMAZON",70000,"2019-10-10"),(2,2,"BNY",50000,"2020-8-10"),(3,4,"DB",75000,"2022-8-8"),(4,5,"BMC",90000,"2021-10-11"),(5,3,"MASTERCARD",40000,"2021-5-7");

SELECT * FROM STUDENT NATURAL JOIN PLACE;
SELECT STUDENT.*, PLACE.COMPNAME, PLACE.PACKAGE FROM STUDENT NATURAL JOIN PLACE;
SELECT STUDENT.SID,STUDENT.SNAME,PLACE.COMPNAME,PLACE.PACKAGE FROM STUDENT INNER JOIN PLACE WHERE STUDENT.DRIVEID=PLACE.DRIVEID;
SELECT STUDENT.SID,STUDENT.SNAME,PLACE.COMPNAME,PLACE.PACKAGE FROM STUDENT LEFT JOIN PLACE ON STUDENT.DRIVEID=PLACE.DRIVEID;


SELECT TRAINING2.TID,TRAINING2.TFEE,PLACE.COMPNAME,PLACE.PACKAGE FROM TRAINING2 LEFT JOIN PLACE ON TRAINING2.TCOMPNAME=PLACE.COMPNAME;
SELECT * FROM TRAINING2 LEFT JOIN PLACE ON TRAINING2.TCOMPNAME=PLACE.COMPNAME;
SELECT * FROM PLACE RIGHT JOIN TRAINING2 ON TRAINING2.TCOMPNAME=PLACE.COMPNAME;
SELECT STUDENT.*, PLACE.COMPNAME FROM STUDENT INNER JOIN PLACE WHERE STUDENT.DRIVEID=PLACE.DRIVEID; 
SELECT STUDENT.SNAME,STUDENT.SBRANCH,PLACE.PACKAGE FROM STUDENT NATURAL JOIN PLACE WHERE PLACE.PACKAGE=55;
SELECT TRAINING2.TCOMPNAME, STUDENT.SNAME, TRAINING2.TFEE FROM STUDENT NATURAL JOIN TRAINING2 WHERE TRAINING2.TFEE>=50000;
SELECT TRAINING2.*,STUDENT.SNAME FROM TRAINING NATURAL JOIN STUDENT WHERE STUDENT.SNAME="ARYAN" AND TYEAR="2019-10-10";
