CREATE TABLE OLD(
    OID INT PRIMARY KEY,
    ONAME VARCHAR(255)
);

CREATE TABLE NEW(
    NID INT PRIMARY KEY,
    NNAME VARCHAR(255)
);

INSERT INTO OLD VALUES(1,"ARYAN"),(2,"ROHIT"),(3,"NEHIL"),(4,"NIRMAL");
INSERT INTO NEW VALUES(2,"ROHIT"),(5,"MANAS"),(6,"ATHARVA"),(7,"MODEL");

SELECT * FROM OLD;
SELECT * FROM NEW;

DELIMITER //
CREATE PROCEDURE ADDTO()
BEGIN
DECLARE CURRID INT DEFAULT 0;
DECLARE CURRNAME VARCHAR(255);
DECLARE DONE INT DEFAULT FALSE;
DECLARE NEW_CURSOR CURSOR FOR SELECT NID,NNAME FROM NEW WHERE NID NOT IN (SELECT OID FROM OLD);
DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE=TRUE;

OPEN NEW_CURSOR;
INLOOP:LOOP
FETCH NEW_CURSOR INTO CURRID,CURRNAME;
IF DONE THEN LEAVE INLOOP;
END IF;
INSERT INTO OLD VALUES(CURRID,CURRNAME);
END LOOP;
CLOSE NEW_CURSOR ;

END;
//

DELIMITER ;

CALL ADDTO();
SELECT * FROM OLD;
SELECT * FROM NEW;



2 done
3 done
4 done
5 done
6 done
7 done
8 
9 done
10 done
11 
12 
