CREATE TABLE LIBRARY(
    ID INT NOT NULL PRIMARY KEY,
    BOOK_NAME VARCHAR(255) NOT NULL,
    TOTAL_COPIES INT NOT NULL
);

CREATE TABLE LIBRARY_AUDIT(
    ID INT NOT NULL,
    BOOK_NAME VARCHAR(255) NOT NULL,
    TOTAL_COPIES INT NOT NULL,
    STATUS VARCHAR(255)
);

CREATE TRIGGER BEFORE_UPDATE
BEFORE UPDATE
ON LIBRARY
FOR EACH ROW
INSERT INTO LIBRARY_AUDIT SET ID=OLD.ID,BOOK_NAME=OLD.BOOK_NAME,TOTAL_COPIES=NEW.TOTAL_COPIES,STATUS='BEFORE UPDATE';


CREATE TRIGGER BEFORE_DELETE
BEFORE DELETE
ON LIBRARY
FOR EACH ROW
INSERT INTO LIBRARY_AUDIT SET ID=OLD.ID,BOOK_NAME=OLD.BOOK_NAME,TOTAL_COPIES=OLD.TOTAL_COPIES,STATUS='BEFORE DELETE';


CREATE TRIGGER BEFORE_INSERT
BEFORE INSERT
ON LIBRARY
FOR EACH ROW
INSERT INTO LIBRARY_AUDIT SET ID=NEW.ID,BOOK_NAME=NEW.BOOK_NAME,TOTAL_COPIES=NEW.TOTAL_COPIES,STATUS='BEFORE INSERT';